ZSH=$HOME/.oh-my-zsh

ZSH_THEME="bramw"

# Git Aliasses
alias gs="git status"
alias gpl="git pull"
alias gps="git push"
alias gc="git commit"
alias gco="git checkout"
alias gca="git commit -a"
alias gmr="git merge"
alias gl='git log --graph --pretty=format:"%h (%an: %ar): %s"'

# Directory Aliasses
alias r="cd ~/rails/"
alias j="cd ~/java/"
alias gt="bundle show --paths | xargs ctags -R -a *"

alias rvmrc="rvm --rvmrc --create"
alias rvmrv="rvm --create --ruby-version use"

alias be="bundle exec"
alias clojure="rlwrap java -cp /clojure/clojure.jar clojure.main"
export EDITOR='vim'

plugins=(git gem bundler redis-cli rvm lol history-substring-search ruby rails3 golang colored-man extract)

source $ZSH/oh-my-zsh.sh

export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export P4CONFIG=.p4config
export P4EDITOR=vim

export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/bin/g4bin:/usr/local/sbin:/usr/X11/

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

function lt() { ls -ltrsa "$@" | tail; }
function psgrep() { ps axu | grep -v grep | grep "$@" -i --color=auto; }
function fname() { find . -iname "*$@*"; }

unsetopt correct_all
unsetopt share_history
DISABLE_CORRECTION="true"

function ctags_with_gems {
  gem_folder=""
  if hash rvm 2>/dev/null; then
    gem_folder=`rvm gemdir | tail -n1`
  else
    gem_folder =`ruby -r rubygems -e "puts Gem.path.to_s" | sed 's/[^"]*\"\([^"]*\)\".*/\1/'`
  fi

  languages="-javascript,-sql"
  ctags -Rf.git/tags.$$ --exclude=.git --exclude=./log --exclude=./tmp --languages=${languages} $PWD ${gem_folder} 2>/dev/null
  mv .git/tags{.$$,}
}
